INSERT INTO lictb001_prompt (nu_prompt, co_chave_prompt, de_prompt) VALUES (nextval('licsq001_prompt'), 'CREATE_CHAT_REQUISITOS', 'inserir o prompt aqui...');
INSERT INTO lictb001_prompt (nu_prompt, co_chave_prompt, de_prompt) VALUES (nextval('licsq001_prompt'), 'CREATE_USER_STORY', 'inserir o prompt aqui...');
INSERT INTO lictb001_prompt (nu_prompt, co_chave_prompt, de_prompt) VALUES (nextval('licsq001_prompt'), 'CREATE_SSD_SPEC', 'inserir o prompt aqui...');
INSERT INTO lictb001_prompt (nu_prompt, co_chave_prompt, de_prompt) VALUES (nextval('licsq001_prompt'), 'CREATE_SSD_PLAN', 'inserir o prompt aqui...');
INSERT INTO lictb001_prompt (nu_prompt, co_chave_prompt, de_prompt) VALUES (nextval('licsq001_prompt'), 'CREATE_SSD_TASK', 'inserir o prompt aqui...');
INSERT INTO lictb001_prompt (nu_prompt, co_chave_prompt, de_prompt) VALUES (nextval('licsq001_prompt'), 'CREATE_SSD_IMPL', 'inserir o prompt aqui...');
INSERT INTO lictb002_projeto (nu_projeto, sg_projeto, no_projeto, de_constituicao) VALUES (nextval('licsq002_projeto'), 'SITAR', 'Sistema de Tarefas', 'Constituicao inicial do projeto SDD Flow.');
INSERT INTO lictb003_repositorio_codigo (nu_repositorio_codigo, no_repositorio,	de_caminho_repositorio, de_url_repositorio, no_branch,de_constituicao,de_estrutura,ic_tipo_repositorio,de_extensoes_arquivos_fonte,nu_projeto,co_comando_compilacao) VALUES (nextval('licsq003_repositorio_codigo'),'tarefas-frontend','/tmp/tarefas-frontend','https://github.com/gustavocontabeis/tarefas-frontend.git','master','','','F','',currval('licsq002_projeto'),'');
INSERT INTO lictb003_repositorio_codigo (nu_repositorio_codigo, no_repositorio,	de_caminho_repositorio, de_url_repositorio, no_branch,de_constituicao,de_estrutura,ic_tipo_repositorio,de_extensoes_arquivos_fonte,nu_projeto,co_comando_compilacao) VALUES (nextval('licsq003_repositorio_codigo'),'tarefas-backend','/tmp/tarefas-backend','https://github.com/gustavocontabeis/tarefas-backend.git','master','','','B','',currval('licsq002_projeto'),'');
